## EJERCICIO DE REPASO: MATRICES, ESTADÍSTICA Y REGRESIÓN LINEAL


---

### PARTE A — MATRICES

In [1]:
import numpy as np

# Definimos las matrices para los ejercicios
A = np.array([[2,0],[1,4],[3,5]])
B = np.array([[6,9,2],[8,1,7]])

print("Matriz A:")
print(A)
print("\nMatriz B:")
print(B)

Matriz A:
[[2 0]
 [1 4]
 [3 5]]

Matriz B:
[[6 9 2]
 [8 1 7]]


#### Ejercicio 1

Sea:
```
A = [[2,0],
     [1,4],
     [3,5]]
B = [[6,9,2],
     [8,1,7]]
```

a) Dimensiones de A y B.

b) Elementos A_3,2 y B_2,1.

c) ¿Es posible sumar A + B? Justifica.

In [2]:
# Solución Ejercicio 1
# Escribe aquí tu solución para el Ejercicio 1

In [3]:
C = np.array([[4,1],[-2,3]])
D = np.array([[0,5],[6,-1]])

print("Matriz C:")
print(C)
print("\nMatriz D:")
print(D)

Matriz C:
[[ 4  1]
 [-2  3]]

Matriz D:
[[ 0  5]
 [ 6 -1]]


#### Ejercicio 2

Sea:
```
C = [[4,1],
     [-2,3]]
D = [[0,5],
     [6,-1]]
```

a) C + D.

b) C - D.

c) Condición para sumar matrices.

In [4]:
# Solución Ejercicio 2
# Escribe aquí tu solución para el Ejercicio 2

In [5]:
E = np.array([[2,-1,3],[0,4,1]])
alfa = -2

print("Matriz E:")
print(E)
print(f"Escalar alfa: {alfa}")

Matriz E:
[[ 2 -1  3]
 [ 0  4  1]]
Escalar alfa: -2


#### Ejercicio 3

Sea:
```
E = [[2,-1,3],
     [0,4,1]]
α = -2
```

a) -2E.

b) Dimensiones resultantes.

In [6]:
# Solución Ejercicio 3
# Escribe aquí tu solución para el Ejercicio 3

In [7]:
F = np.array([[2,1],[0,3]])
G = np.array([[1,4],[5,2]])

print("Matriz F:")
print(F)
print("\nMatriz G:")
print(G)

Matriz F:
[[2 1]
 [0 3]]

Matriz G:
[[1 4]
 [5 2]]


#### Ejercicio 4

Sea:
```
F = [[2,1],
     [0,3]]
G = [[1,4],
     [5,2]]
```

a) FG.

b) ¿FG = GF? Demuéstralo con el cálculo.

c) Condición del producto matricial.

In [8]:
# Solución Ejercicio 4
# Escribe aquí tu solución para el Ejercicio 4

In [9]:
H = np.array([[3,1,0],[2,5,4]])

print("Matriz H:")
print(H)

Matriz H:
[[3 1 0]
 [2 5 4]]


#### Ejercicio 5

Sea:
```
H = [[3,1,0],
     [2,5,4]]
```

a) H^T (Transpuesta de H).

b) Dimensión de la transpuesta.

In [10]:
# Solución Ejercicio 5
# Escribe aquí tu solución para el Ejercicio 5

---

### PARTE B — ESTADÍSTICA Y MODELOS

In [11]:
X_ej6 = np.array([1,3,3,4,6,8])
print(f"Datos para Ejercicio 6 (X): {X_ej6}")

Datos para Ejercicio 6 (X): [1 3 3 4 6 8]


#### Ejercicio 6

Sea el conjunto de datos:
```
X = [1,3,3,4,6,8]
```

a) Media.

b) Varianza (poblacional).

c) Desviación estándar (poblacional).

In [12]:
# Solución Ejercicio 6
# Escribe aquí tu solución para el Ejercicio 6

In [13]:
X_ej7 = np.array([2,4,6,8,10])
Y_ej7 = np.array([1,2,4,3,5])

print(f"Datos para Ejercicio 7 (X): {X_ej7}")
print(f"Datos para Ejercicio 7 (Y): {Y_ej7}")

Datos para Ejercicio 7 (X): [ 2  4  6  8 10]
Datos para Ejercicio 7 (Y): [1 2 4 3 5]


#### Ejercicio 7

Sea los conjuntos de datos:
```
X = [2,4,6,8,10]
Y = [1,2,4,3,5]
```

a) Covarianza (poblacional).

b) Interpretación de la covarianza obtenida.

In [14]:
# Solución Ejercicio 7
# Escribe aquí tu solución para el Ejercicio 7

#### Ejercicio 8

**Coeficiente de correlación de Pearson (r):**

a) Definición.

b) Rango e interpretación de sus valores.

#### Ejercicio 9

**Modelo de regresión lineal simple:** `y = β0 + β1 x + ε`

a) Significado de cada uno de los términos del modelo.

b) Objetivo del método de Mínimos Cuadrados Ordinarios (OLS).

#### Ejercicio 10

Definición de SST (Suma Total de Cuadrados), SSR (Suma de Cuadrados de la Regresión) y SSE (Suma de Cuadrados del Error).

Relación matemática entre ellas.

#### Ejercicio 11

**Coeficiente de determinación R²:**

Definición e interpretación de su valor.

---

### PARTE C — APLICACIÓN (Regresión Lineal Simple)

In [15]:
X_app = np.array([0,1,2,3,4])
Y_app = np.array([1,2.2,2.9,3.8,5.1])

print(f"Datos X para aplicación: {X_app}")
print(f"Datos Y para aplicación: {Y_app}")

Datos X para aplicación: [0 1 2 3 4]
Datos Y para aplicación: [1.  2.2 2.9 3.8 5.1]


#### Ejercicio 12

Sea los conjuntos de datos:
```
X = [0,1,2,3,4]
Y = [1,2.2,2.9,3.8,5.1]
```

Construcción de la matriz de diseño (matriz X grande) para el modelo de regresión lineal simple, asumiendo un intercepto.

In [16]:
# Solución Ejercicio 12
# Escribe aquí tu solución para el Ejercicio 12

#### Ejercicio 13

Cálculo de los coeficientes `β` (β0 y β1) usando la fórmula matricial de Mínimos Cuadrados Ordinarios (OLS): `β = (XᵀX)⁻¹XᵀY`.

In [17]:
# Solución Ejercicio 13
# Escribe aquí tu solución para el Ejercicio 13

#### Ejercicio 14

Calcula los valores predichos (`ŷ`) y los residuos (`e`) para cada observación utilizando los coeficientes `β` obtenidos.

In [18]:
# Solución Ejercicio 14
# Escribe aquí tu solución para el Ejercicio 14

#### Ejercicio 15

Calcula e interpreta el Coeficiente de Determinación (R²) para el modelo ajustado.

In [19]:
# Solución Ejercicio 15
# Escribe aquí tu solución para el Ejercicio 15